# Generated by Django 2.1.2 on 2018-11-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=28)),
                ('state_province_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('locale_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Locale')),
            ],
        ),
    ]
