# Generated by Django 2.1.2 on 2018-11-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locale',
            unique_together={('city', 'state_province_code')},
        ),
    ]
