# Generated by Django 2.1.2 on 2018-11-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181112_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_modified_datetime',
            new_name='last_modified',
        ),
    ]
