from base.models import Locale

Locale.objects.bulk_create(
    [Locale(city='New York', state_province_code='NY'),
    Locale(city='Los Angeles', state_province_code='CA'),
    Locale(city='Chicago', state_province_code='IL'),
    Locale(city='Houston', state_province_code='TX'),
    Locale(city='Phoenix', state_province_code='AZ'),
    Locale(city='Philadelphia', state_province_code='PA'),
    Locale(city='San Antonio', state_province_code='TX'),
    Locale(city='San Diego', state_province_code='CA'),
    Locale(city='Dallas', state_province_code='TX'),
    Locale(city='San Jose', state_province_code='CA'),
    Locale(city='Austin', state_province_code='TX'),
    Locale(city='Jacksonville', state_province_code='FL'),
    Locale(city='San Francisco', state_province_code='CA'),
    Locale(city='Columbus', state_province_code='OH'),
    Locale(city='Fort Worth', state_province_code='TX'),
    Locale(city='Indianapolis', state_province_code='IN'),
    Locale(city='Charlotte', state_province_code='NC'),
    Locale(city='Seattle', state_province_code='WA'),
    Locale(city='Denver', state_province_code='CO'),
    Locale(city='Washington', state_province_code='DC'),
    Locale(city='Boston', state_province_code='MA'),
    Locale(city='El Paso', state_province_code='TX'),
    Locale(city='Detroit', state_province_code='MI'),
    Locale(city='Nashville', state_province_code='TN'),
    Locale(city='Memphis', state_province_code='TN'),
    Locale(city='Portland', state_province_code='OR'),
    Locale(city='OK City', state_province_code='OK'),
    Locale(city='Las Vegas', state_province_code='NV'),
    Locale(city='Louisville', state_province_code='KY'),
    Locale(city='Baltimore', state_province_code='MD'),
    Locale(city='Milwaukee', state_province_code='WI'),
    Locale(city='Albuquerque', state_province_code='NM'),
    Locale(city='Tucson', state_province_code='AZ'),
    Locale(city='Fresno', state_province_code='CA'),
    Locale(city='Sacramento', state_province_code='CA'),
    Locale(city='Mesa', state_province_code='AZ'),
    Locale(city='Kansas City', state_province_code='MO'),
    Locale(city='Atlanta', state_province_code='Georgia'),
    Locale(city='Long Beach', state_province_code='CA'),
    Locale(city='Omaha', state_province_code='NE'),
    Locale(city='Raleigh', state_province_code='NC'),
    Locale(city='CO Springs', state_province_code='CO'),
    Locale(city='Miami', state_province_code='FL'),
    Locale(city='Virginia Beach', state_province_code='VA'),
    Locale(city='Oakland', state_province_code='CA'),
    Locale(city='Minneapolis', state_province_code='MN'),
    Locale(city='Tulsa', state_province_code='OK'),
    Locale(city='Arlington', state_province_code='TX'),
    Locale(city='New Orleans', state_province_code='LA'),
    Locale(city='Wichita', state_province_code='KS'),
    Locale(city='Cleveland', state_province_code='OH'),
    Locale(city='Tampa', state_province_code='FL'),
    Locale(city='Bakersfield', state_province_code='CA'),
    Locale(city='Aurora', state_province_code='CO'),
    Locale(city='Anaheim', state_province_code='CA'),
    Locale(city='Honolulu', state_province_code='HI'),
    Locale(city='Santa Ana', state_province_code='CA'),
    Locale(city='Riverside', state_province_code='CA'),
    Locale(city='Corpus Christi', state_province_code='TX'),
    Locale(city='Lexington', state_province_code='KY'),
    Locale(city='Stockton', state_province_code='CA'),
    Locale(city='St. Louis', state_province_code='MO'),
    Locale(city='Saint Paul', state_province_code='MN'),
    Locale(city='Henderson', state_province_code='NV'),
    Locale(city='Pittsburgh', state_province_code='PA'),
    Locale(city='Cincinnati', state_province_code='OH'),
    Locale(city='Anchorage', state_province_code='AK'),
    Locale(city='Greensboro', state_province_code='NC'),
    Locale(city='Plano', state_province_code='TX'),
    Locale(city='Newark', state_province_code='NJ'),
    Locale(city='Lincoln', state_province_code='NE'),
    Locale(city='Orlando', state_province_code='FL'),
    Locale(city='Irvine', state_province_code='CA'),
    Locale(city='Toledo', state_province_code='OH'),
    Locale(city='Jersey City', state_province_code='NJ'),
    Locale(city='Chula Vista', state_province_code='CA'),
    Locale(city='Durham', state_province_code='NC'),
    Locale(city='Fort Wayne', state_province_code='IN'),
    Locale(city='St. Petersburg', state_province_code='FL'),
    Locale(city='Laredo', state_province_code='TX'),
    Locale(city='Buffalo', state_province_code='NY'),
    Locale(city='Madison', state_province_code='WI'),
    Locale(city='Lubbock', state_province_code='TX'),
    Locale(city='Chandler', state_province_code='AZ'),
    Locale(city='Scottsdale', state_province_code='AZ'),
    Locale(city='Reno', state_province_code='NV'),
    Locale(city='Glendale', state_province_code='AZ'),
    Locale(city='Norfolk', state_province_code='VA'),
    Locale(city='Winston–Salem', state_province_code='NC'),
    Locale(city='North Las Vegas', state_province_code='NV'),
    Locale(city='Gilbert', state_province_code='AZ'),
    Locale(city='Chesapeake', state_province_code='VA'),
    Locale(city='Irving', state_province_code='TX'),
    Locale(city='Hialeah', state_province_code='FL'),
    Locale(city='Garland', state_province_code='TX'),
    Locale(city='Fremont', state_province_code='CA'),
    Locale(city='Richmond', state_province_code='VA'),
    Locale(city='Boise', state_province_code='ID'),
    Locale(city='Baton Rouge', state_province_code='LA'),
    Locale(city='Des Moines', state_province_code='IA')]
)
